# RTD configuration v2
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz

sphinx:
  configuration: source/conf.py

python:
  install:
    - requirements: requirements.txt

# Enable all formats (HTML is default; add PDF/EPUB if you want)
formats:
  - htmlzip
  - epub
  - pdf